In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.datasets import load_digits, load_iris
from sklearn.model_selection import train_test_split
from pca import pca as MyPCA

# Load Digit Dataset

In [3]:
digits = load_digits()

# sklearn PCA

In [4]:
pca = PCA(n_components=2, random_state=17).fit(digits.data)

In [5]:
data_pca = pca.transform(digits.data)

In [6]:
pca.explained_variance_ratio_, pca.explained_variance_, pca.singular_values_, pca.components_

(array([0.14890594, 0.13618771]),
 array([179.0069301 , 163.71774688]),
 array([567.0065665 , 542.25185421]),
 array([[ 0.00000000e+00, -1.73094681e-02, -2.23428857e-01,
         -1.35913278e-01, -3.30322665e-02, -9.66340984e-02,
         -8.32945456e-03,  2.26900026e-03, -3.20516383e-04,
         -1.19308907e-01, -2.44451685e-01,  1.48512759e-01,
         -4.67319434e-02, -2.17740753e-01, -1.48136832e-02,
          4.47779666e-03, -4.94135455e-05, -7.95419376e-02,
          8.33951158e-02,  2.15915335e-01, -1.72126830e-01,
         -1.63712098e-01,  2.86444619e-02,  4.23251992e-03,
          9.85489009e-05,  6.42319132e-02,  2.54093298e-01,
         -3.56770815e-02, -2.09462577e-01, -4.31311343e-02,
          5.13118922e-02,  2.13422826e-04,  0.00000000e+00,
          1.59950878e-01,  3.68690771e-01,  1.64406850e-01,
          8.52007739e-02,  3.72982661e-02,  2.15867080e-02,
          0.00000000e+00,  1.28865584e-03,  1.06945272e-01,
          3.03067438e-01,  2.47813030e-01,  2.0963

In [7]:
data_pca

array([[ -1.25946642,  21.27488339],
       [  7.95761212, -20.76869896],
       [  6.99192263,  -9.95598631],
       ...,
       [ 10.80128374,  -6.96025215],
       [ -4.87209983,  12.42395343],
       [ -0.34439037,   6.36554925]])

# Our Implementation

In [8]:
pca1 = MyPCA(n_components=2, solver='svd')

In [9]:
pca1.fit(digits.data)

In [10]:
data_pca1 = pca1.transform(digits.data)

In [11]:
pca1.explained_variance_ratio_, pca1.explained_variance_, pca1.singular_values_, pca1.components_

(array([0.14890594, 0.13618771]),
 array([179.0069301 , 163.71774688]),
 array([567.0065665 , 542.25185421]),
 array([[-1.77484909e-19, -1.73094651e-02, -2.23428835e-01,
         -1.35913304e-01, -3.30323092e-02, -9.66340844e-02,
         -8.32943805e-03,  2.26900082e-03, -3.20516495e-04,
         -1.19308905e-01, -2.44451676e-01,  1.48512745e-01,
         -4.67319410e-02, -2.17740744e-01, -1.48136776e-02,
          4.47779518e-03, -4.94136398e-05, -7.95419375e-02,
          8.33951454e-02,  2.15915342e-01, -1.72126801e-01,
         -1.63712098e-01,  2.86444452e-02,  4.23251803e-03,
          9.85488574e-05,  6.42319144e-02,  2.54093316e-01,
         -3.56771026e-02, -2.09462569e-01, -4.31311420e-02,
          5.13118688e-02,  2.13422732e-04, -0.00000000e+00,
          1.59950883e-01,  3.68690774e-01,  1.64406827e-01,
          8.52007908e-02,  3.72982855e-02,  2.15866980e-02,
         -0.00000000e+00,  1.28865585e-03,  1.06945287e-01,
          3.03067457e-01,  2.47813041e-01,  2.0963

In [12]:
data_pca1

array([[ -1.25946645,  21.27488348],
       [  7.9576113 , -20.76869896],
       [  6.99192297,  -9.95598641],
       ...,
       [ 10.8012837 ,  -6.96025223],
       [ -4.87210009,  12.42395362],
       [ -0.34438963,   6.36554919]])

### eig solver

In [22]:
pca_eig = MyPCA(n_components=2, solver='eig')

In [23]:
pca_eig.fit(digits.data)

In [24]:
data_eig = pca_eig.transform(digits.data)

In [25]:
pca_eig.explained_variance_ratio_, pca_eig.explained_variance_, pca_eig.singular_values_, pca_eig.components_

(array([0.14890594, 0.13618771]),
 array([178.90731578, 163.62664073]),
 array([566.84877978, 542.10095624]),
 array([[-0.00000000e+00,  1.73094651e-02,  2.23428835e-01,
          1.35913304e-01,  3.30323092e-02,  9.66340844e-02,
          8.32943805e-03, -2.26900082e-03,  3.20516495e-04,
          1.19308905e-01,  2.44451676e-01, -1.48512745e-01,
          4.67319410e-02,  2.17740744e-01,  1.48136776e-02,
         -4.47779518e-03,  4.94136398e-05,  7.95419375e-02,
         -8.33951454e-02, -2.15915342e-01,  1.72126801e-01,
          1.63712098e-01, -2.86444452e-02, -4.23251803e-03,
         -9.85488574e-05, -6.42319144e-02, -2.54093316e-01,
          3.56771026e-02,  2.09462569e-01,  4.31311420e-02,
         -5.13118688e-02, -2.13422732e-04, -0.00000000e+00,
         -1.59950883e-01, -3.68690774e-01, -1.64406827e-01,
         -8.52007908e-02, -3.72982855e-02, -2.15866980e-02,
         -0.00000000e+00, -1.28865585e-03, -1.06945287e-01,
         -3.03067457e-01, -2.47813041e-01, -2.0963

In [26]:
data_eig

array([[  1.25946645,  21.27488348],
       [ -7.9576113 , -20.76869896],
       [ -6.99192297,  -9.95598641],
       ...,
       [-10.8012837 ,  -6.96025223],
       [  4.87210009,  12.42395362],
       [  0.34438963,   6.36554919]])

# Iris Dataset

Let's try to plot 3 components after PCA.<br>
https://scikit-learn.org/stable/auto_examples/decomposition/plot_pca_iris.html#sphx-glr-auto-examples-decomposition-plot-pca-iris-py

In [ ]:
from mpl_toolkits.mplot3d import Axes3D

In [ ]:
def plot_components(X, y):
    fig = plt.figure(1, figsize=(12, 8))
    plt.clf()
    ax = Axes3D(fig, rect=[0, 0, .95, 1], elev=48, azim=134)
    
    for name, label in [('Setosa', 0), ('Versicolour', 1), ('Virginica', 2)]:
        ax.text3D(X[y == label, 0].mean(),
              X[y == label, 1].mean() + 1.5,
              X[y == label, 2].mean(), name,
              horizontalalignment='center',
              bbox=dict(alpha=.5, edgecolor='w', facecolor='w'))

    # Reorder the labels to have colors matching the cluster results
    y = np.choose(y, [1, 2, 0]).astype(np.float)
    ax.scatter(X[:, 0], X[:, 1], X[:, 2], c=y, cmap=plt.cm.nipy_spectral,
           edgecolor='k')

    ax.w_xaxis.set_ticklabels([])
    ax.w_yaxis.set_ticklabels([])
    ax.w_zaxis.set_ticklabels([])

    plt.show()

In [ ]:
iris = load_iris()

In [ ]:
X, y = iris.data, iris.target

# sklearn

In [ ]:
pca_3d = PCA(n_components=3, random_state=17).fit(X)

In [ ]:
X_3d = pca_3d.transform(X)

In [ ]:
plot_components(X_3d, y)

# Our's: Solver:svd

In [ ]:
pca_3d_svd = MyPCA(n_components=3)

In [ ]:
pca_3d_svd.fit(X)

In [ ]:
X_3d_svd = pca_3d_svd.transform(X)

In [ ]:
plot_components(X_3d_svd, y)

# Our's: Solver:eig fit_transform

In [ ]:
pca_3d_eig = MyPCA(n_components=3, solver='eig')

In [ ]:
X_3d_eig = pca_3d_eig.fit_transform(X)

In [ ]:
plot_components(X_3d_eig, y)

In [ ]:
pca_3d_svd.explained_variance_

In [ ]:
pca_3d_eig.explained_variance_